version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: auction
    networks:
      - kantakap-network

  kantakap-auction-file-handler:
    build: https://github.com/kantakap/auction-file-handler.git
    container_name: kantakap-auction-file-handler
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
    networks:
      - kantakap-network

  kantakap-auction-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kantakap-auction-api
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - mongodb
    networks:
      - kantakap-network
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

networks:
  kantakap-network:
    driver: bridge